# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 03:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namepet', models.CharField(max_length=6)),
                ('datenac', models.DateField()),
                ('edad', models.IntegerField()),
                ('nameraza', models.CharField(max_length=15)),
                ('amo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=15)),
                ('destinatario', models.CharField(max_length=15)),
                ('asunto', models.CharField(max_length=10)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
