# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20160106_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='/mascotas'),
        ),
    ]
